image: docker:stable
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - release

before_script:
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

build:
  stage: build
  script:
    - >
      docker build
      --pull
      --cache-from "$CI_REGISTRY_IMAGE:latest"
      --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      .
  only:
    - master

push:
  stage: release
  variables:
    GIT_STRATEGY: none
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:-latest}
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:-latest}
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master