image: golang:1.15-buster

stages:
  - release

before_script:
  - export GOPATH=${CI_PROJECT_DIR}/.cache
  - export GOARCH=amd64
  - export OSS="linux freebsd netbsd darwin"
  - export BASEURL="https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}"

release:
  stage: release
  script:
    - for os in ${OSS}; do GOOS=$os GOARCH=${GOARCH} make cross; done
    - apt-get update -qq && apt-get -qq -y install curl jq
    - /bin/sh mkrel.sh snip
  artifacts:
    paths:
      - snip_*
  only:
    - tags