#!/bin/sh

set -e

export SNIP_CWD=`pwd`
cd `dirname $0`

if [ ! -z "$SNIP_GO_BUILD_PLUGINS" ]; then
  ./go-build-plugins $SNIP_CWD
fi

if [ ! -t 0 ]; then
  exec cat /dev/stdin | go run "main.go" $@
else
  exec go run "main.go" $@
fi
