package play

import (
	"os"
	"path/filepath"
	"strings"
	"time"

	"gitlab.com/youtopia.earth/ops/snip/errors"
)

func BuildPlaybook(app App, playbook []*Play) {

	cfg := app.GetConfig()

	now := time.Now()
	nowText := now.Format("2006-01-02 15:04:05")

	for _, p := range playbook {

		file := cfg.BuildDir + "/snippets/" + p.Name + ".bash"
		dir := filepath.Dir(file)
		os.MkdirAll(dir, os.ModePerm)

		f, err := os.OpenFile(file, os.O_APPEND|os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0755)
		errors.Check(err)
		defer f.Close()
		outputAppend := func(str string) {
			_, err := f.WriteString(str)
			errors.Check(err)
		}

		outputAppend("#!/usr/bin/env bash\n\n")
		outputAppend("# play snippet: " + p.Name + "\n")
		outputAppend("# generated by snip on " + nowText + "\n\n")
		outputAppend("set -e\n\n")

		for _, codeBlock := range p.CodeBlocks {
			content := codeBlock.Content
			content = strings.Trim(content, "\n")
			outputAppend(content + "\n")
		}

	}
}
